export const SET_SUBJECT = "SET_SUBJECT"
export const SET_LOCATION_REQUEST = "SET_LOCATION_REQUEST"
export const SET_LOCATION_SUCCESS = "SET_LOCATION_SUCCESS"
export const SET_LOCATION_ERR = "SET_LOCATION_ERR"
